### ISSUE TITLE
How to support new AR releases

### ISSUE THREAD

**Issue by EdVanDance** [DanielT/autosar-data#17]
Hello,

this isn't really an issue, rather a question. I couldn't think of a better place to address this.

I was wondering if you have any plans to document or maybe even automate the integration of new AR releases?

My co-workers and me are really liking this, especially the python bindings. We are afraid that you stop the maintenance at some point. That is our only concern which is holding us back from broader adoption.

Looking forward to your thoughts on this.

Regards,
Ed

**Comment by DanielT** [comment]
The integration is largely automated.
If you look at the data tables in autosar-data-specification, you will easily see that this is not something a person could write directly. What I did was to write a tool that parses the xsd files released as part of the Autosar standard.

Until now I had never bothered to set that repository to public, because:
- I assumed that no one would care
- the code isn't great - it works, but that's the best thing about it
- I can't provide the xsd files you need as the input, since the copyright on these files does not allow me to redistribute them

Anyway, here you go: [autosar-xsd-mangler](https://github.com/DanielT/autosar-xsd-mangler)

**Comment by EdVanDance** [comment]
I thought so already 😃 

Thank you very much for sharing this 👍
